#ifndef OCEAN_H
#define OCEAN_H
#include "ships.h"
#include <vector>
//do not edit this file!
const int SIDES=10;//jim add
class Ocean{
private:
    int shotsFired;
    int hitCount;
    int shipsSunk;
    static int totalShips; //jim add
public:
    std::vector<std::vector<Ship*>> ships;
    Ocean();
    ~Ocean();
    int getRando(int max=SIDES); //jim add
    void placeOneShipRandomly(Ship* ship); //jim add
    void placeAllShipsRandomly();
    bool isOccupied(int row, int column);
    bool shootAt(int row, int column);
    int getShotsFired();
    int getHitCount();
    int getShipsSunk();
    bool isGameOver();
    void print();

};
#endif
